#!/usr/bin/env bash
# Displays "Best School" 10 times using an while loop but for 9th iteration adds "Hi".

index=0

while [ $index -lt 10 ]
do
    if [ $index -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( index++ ))
done