#!/usr/bin/env bash
# Displays displays bad luck for the 4th loop iteration, good luck for the 8th loop iteration and Best School for the other iterations

index = 0
while [ index -lt 10 ]; do
    if [index -eq 3]
        echo "bad luck"
    elif [index -eq 7]
        echo "good luck"
    else
        echo "Best School"
done
