#!/usr/bin/env bash
# Displays a numbers from 1 - 20 and displays another texts next to it on 4th, 9th and 17th iteration

index=1

while [ $index -le 20 ]
do
    echo $index
    case "$index" in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( index++ ))
done