#!/usr/bin/env bash
# Displays a numbers from 1 - 20 and displays another texts next to it on 4th, 9th and 17th iteration

index = 0
while [$index -lt 20]; do
    echo $index
    if [$index -eq 3]
        echo "bad luck from China"
    elif [$index -eq 9]
        echo "bad luck from Japan"
    elif [$index -eq 16]
        echo "bad luck from Italy"
done