#!/usr/bin/env bash
# Displays a numbers from 1 - 20 and displays another texts next to it on 4th, 9th and 17th iteration

index = 1

while [ $index -le 20 ]
do
    echo $index
    if [ $index -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $index -eq 9 ]
    then
        echo "bad luck from Japan"
    elif [ $index -eq 17 ]
    then
        echo "bad luck from Italy"
    fi
    (( index++ ))
done