#!/usr/bin/env bash
# ssh config file

# Host *
# SendEnv LANG LC_*
# HashKnownHosts yes
# GSSAPIAuthentication yes
# GSSAPIDelegateCredentials no
# IdentityFile ~/.ssh/school
# PasswordAuthentication no

OR
Host 192.168.0.123
IdentityFile ~/.ssh/school
PasswordAuthentication no
